### PR TITLE
Clean up officially supported games

### PR DESCRIPTION
**Pull request by nashmuhandes**

### CODE REVIEW

**Comment by dpjudas** [comment]
I wonder if this is the better way, or if the ini file should instead not create entries for a game until it has actually encountered it.

**Comment by coelckers** [comment]
Why this desire to remove support for these lesser known games? Especially Action Doom 2!

**Comment by dpjudas** [comment]
The motivation for this PR isn't to remove the support (a few extra lines in the code doesn't harm that much).

Rather, it is really about the ini file being spammed with games that the user never encountered. Which is also why I didn't merge the PR in its current form. It would be better if the ini file handling code didn't create entries for stuff unless it was actually actively used/relevant.

**Comment by coelckers** [comment]
Agreed on the latter point, that would definitely be better.

**Comment by CaptainMuskrat** [comment]
I hope this project ends up being a lot leaner and better coded than GZDoom, which is notoriously bloated and performance intensive. Remember the "KISS" philosophy, Keep It Simple Stupid. If a feature doesn't make sense or doesn't add much to the experience, please consider removing it. Sometimes not having a feature is better than having a niche or buggy one.

**Pull request closed without merging**
